<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Action Directory
    |--------------------------------------------------------------------------
    |
    | The root directory where Actions generated by make:action will be created.
    |
    | @value string
    */

    'action_dir' => app_path('Http/Actions'),

    /*
    |--------------------------------------------------------------------------
    | Default Middleware
    |--------------------------------------------------------------------------
    |
    | The default middleware set to use when generating an Action via Artisan.
    |
    | @value array<string>
    */

    'default_middleware' => ['web'],

    /*
    |--------------------------------------------------------------------------
    | API Middleware
    |--------------------------------------------------------------------------
    |
    | The middleware set to use when generating an Action via Artisan
    | and flagging it as --api.
    |
    | @value array<string>
    */

    'api_middleware' => ['api'],

    /*
    |--------------------------------------------------------------------------
    | Use Strict Type Declaration
    |--------------------------------------------------------------------------
    |
    | Flag to declare strict types in generated Actions.
    |
    | @value bool
    */

    'generate_strict_types' => true,
];
